version: "3"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    # restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniopass
    command: server --address ":9000" --console-address ":9001" /data
    volumes:
      - ~/docker-repo/minio:/var/lib/minio

volumes:
  minio_data:
    external: true