### 일반 유저 로그인
POST http://localhost:8080/api/users/login
Content-Type: application/json

{
  "email" : "asdf2345@email.com",
  "password" : "Asdf2345!"
}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.global.set("RefreshToken", response.headers.valueOf("RefreshToken"));
%}

### 파이썬 실행
POST http://localhost:8080/api/coderuns/1/4/runs
Content-Type: application/json
Authorization: {{Authorization}}

{
    "language": "python",
    "code": "print(\"Hello, world!\")"
}

### JavaScript 코드 실행
POST http://localhost:8080/api/coderuns/runs
Content-Type: application/json
Authorization: {{Authorization}}

{
    "teamId": 1,
    "codeKatasId": 1,
    "language": "javascript",
    "code": "console.log(\"Hello, world!\");"
}

### Java 코드 실행
POST http://localhost:8080/api/coderuns/runs
Content-Type: application/json
Authorization: {{Authorization}}

{
    "teamId": 1,
    "codeKatasId": 1,
    "language": "java",
    "code": "public class Main { public static void main(String[] args) { System.out.println(\"Hello, world!\"); } }"
}

###

POST http://localhost:8080/api/coderuns/runs
Content-Type: application/json
Authorization: {{Authorization}}

{
    "teamId": 1,
    "codeKatasId": 1,
    "language": "ruby",
    "code": "puts \"Hello, world!\""
}
